### ISSUE TITLE
Mac 7.4 Binary

### ISSUE THREAD

**Issue by aerickson** [3DprintFIT/netfabb-basic-download#2]
Hi,

Autodesk has discontinued all Mac versions of Netfabb it appears.

I have a Mac v7.4 binary. I don't have installer but can vouch for it.

Please let me know how I can get it to you.

Thanks,
Andy

**Comment by hroncok** [comment]
Would github let you upload the zip here? Or is it too big?

**Comment by aerickson** [comment]
Yeah, I haven't stripped it of manuals and examples yet.

I've sent a link to your email listed on your GitHub profile.

**Comment by hroncok** [comment]
Thanks, will look at it.

**Comment by hroncok** [comment]
I've received a file called netfabb.Free.v74.app.zip trough private channel. Coudl you please provide me same hashes of that file? Here's what I get:

```console
$ md5sum netfabb.Free.v74.app.zip 
0c2843a8f60fa6f6add5cb60304f608d  netfabb.Free.v74.app.zip
$ sha256sum netfabb.Free.v74.app.zip 
f19af5e77f916156f0c6b81875b462aaed6acd9fb02aff3feb5eb50eba6e768a  netfabb.Free.v74.app.zip
```

**Comment by hroncok** [comment]
And upon extracting:

```console
$ md5sum "netfabb Free.app/Contents/MacOS/netfabb_free"
9fbf665eed09a2c9a8c0c088a90384d6  netfabb Free.app/Contents/MacOS/netfabb_free
$ sha256sum "netfabb Free.app/Contents/MacOS/netfabb_free"
62786c6d99b558741661db969fd8546fae4774525b9ab0fed717d1b4296c8146  netfabb Free.app/Contents/MacOS/netfabb_free

```

**Comment by aerickson** [comment]
Sure. Your checksums look good.

I've added the sha256 of the lib directory also.

```
f19af5e77f916156f0c6b81875b462aaed6acd9fb02aff3feb5eb50eba6e768a  netfabb.Free.v74.app.zip
62786c6d99b558741661db969fd8546fae4774525b9ab0fed717d1b4296c8146  netfabb Free.app/Contents/MacOS/netfabb_free

25fbeb76fa2a298e5b083bf8bf15857702eb37ba6ca3a281c24e  netfabb Free.app/Contents/Resources/lib/gmres.dylib
271be62f4655f0de38ba8d50f8d82fbd6cfd0a7ed98be70e0d98034c0dfeaa09  netfabb Free.app/Contents/Resources/lib/lib3ds-netfabb-1.3.dylib
6c54cf1638f6e1598ec4a061f08601c29a5d29177acf837435afe5a47f685a70  netfabb Free.app/Contents/Resources/lib/lib3MF.dylib
2ced766ee821652b3934769491df291fbc86b8111dbabc2c05f8538fdf80e455  netfabb Free.app/Contents/Resources/lib/libgmp.3.5.2.dylib
73a533f0ca1b69fd11fbcee005e83d3abeb902206639e2905620f0080454c241  netfabb Free.app/Contents/Resources/lib/liblua5.1.dylib
268c9702b51014234d01a7520c8e94f1e41a6aadcc13639d7284405e40a8a778  netfabb Free.app/Contents/Resources/lib/libusb-1.0.dylib
501fca08df447837737e4f589719ee7a06966392618b0e78f6d31c73e7a3eb94  netfabb Free.app/Contents/Resources/lib/libxiot.dylib
1da10e22de0e8da8ce9234f6ff54b7929f11cef43cd98c191d05761932a98b27  netfabb Free.app/Contents/Resources/lib/netfabb_unzip.dylib
```

**Comment by hroncok** [comment]
```
7a9835505c8125fbeb76fa2a298e5b083bf8bf15857702eb37ba6ca3a281c24e  netfabb Free.app/Contents/Resources/lib/gmres.dylib
271be62f4655f0de38ba8d50f8d82fbd6cfd0a7ed98be70e0d98034c0dfeaa09  netfabb Free.app/Contents/Resources/lib/lib3ds-netfabb-1.3.dylib
6c54cf1638f6e1598ec4a061f08601c29a5d29177acf837435afe5a47f685a70  netfabb Free.app/Contents/Resources/lib/lib3MF.dylib
2ced766ee821652b3934769491df291fbc86b8111dbabc2c05f8538fdf80e455  netfabb Free.app/Contents/Resources/lib/libgmp.3.5.2.dylib
73a533f0ca1b69fd11fbcee005e83d3abeb902206639e2905620f0080454c241  netfabb Free.app/Contents/Resources/lib/liblua5.1.dylib
268c9702b51014234d01a7520c8e94f1e41a6aadcc13639d7284405e40a8a778  netfabb Free.app/Contents/Resources/lib/libusb-1.0.dylib
501fca08df447837737e4f589719ee7a06966392618b0e78f6d31c73e7a3eb94  netfabb Free.app/Contents/Resources/lib/libxiot.dylib
1da10e22de0e8da8ce9234f6ff54b7929f11cef43cd98c191d05761932a98b27  netfabb Free.app/Contents/Resources/lib/netfabb_unzip.dylib
```

**Comment by hroncok** [comment]
I've removed `__MACOSX/`, `netfabb Free.app/Contents/MacOS/Manual/` and `netfabb Free.app/Contents/MacOS/Examples/`. Hence the overall zip sums will be different, but the stuff inside should have the same hashes. Uploading to https://github.com/3DprintFIT/netfabb-basic-download/releases/tag/v7.4.0

**Comment by hroncok** [comment]
Thank you Andrew.

**Comment by hroncok** [comment]
![netafbb-mac](https://user-images.githubusercontent.com/2401856/33925497-5e7899b4-dfda-11e7-9191-3110794fbfad.png)

**Comment by probonopd** [comment]
Autodesk will quietly murder this tool, too - what'll come next? Subscriptions only, Windows only, Online only, no Free? Oh wait, that's already happening...

**Comment by dkurtycz** [comment]
This Mac version is already too old to run with Catalina or Big Sur.

**Comment by abdoalae** [comment]
> Hi,
> 
> Autodesk has discontinued all Mac versions of Netfabb it appears.
> 
> I have a Mac v7.4 binary. I don't have installer but can vouch for it.
> 
> Please let me know how I can get it to you.
> 
> Thanks, Andy

HI,
 I need the Netfabb for the Mac, could you please send to me 
Thanks!

**Comment by abdoalae** [comment]
> ![netafbb-mac](https://user-images.githubusercontent.com/2401856/33925497-5e7899b4-dfda-11e7-9191-3110794fbfad.png)

Hi,
I need the Netfabb free for thee Mac if you can help with, I am really approached 
Thanks!
