### ISSUE TITLE
“netfabb Free” needs to be updated.

### ISSUE THREAD

**Issue by nepalsingh1** [3DprintFIT/netfabb-basic-download#6]
The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.

**Comment by probonopd** [comment]
"The developer" nowadays is Autodesk.
Which is unfortunate.

Usually everything they buy goes downhill rapidly:
* Linux versions cancelled
* Licensed only as subscriptions
* Things get crazy expensive
* Need to be online
... 

With "crazy expensive" I mean, like 12,512 for 3 years. If you want "Ultimate", or "Local", then they won't even tell you the price unless you speak with one of heir "Netfabb sales experts"...!

![image](https://user-images.githubusercontent.com/2480569/115137862-0cd6e000-a018-11eb-992d-9df980d2318b.png)

But maybe you can reach the developers still under their "old" phone number even though that company apparently has been bought by Autodesk:

![image](https://user-images.githubusercontent.com/2480569/115137909-51fb1200-a018-11eb-950a-e01e0a0619e8.png)

**Comment by nepalsingh1** [comment]
Thanks.

**Comment by mindfulme** [comment]
https://macdownload.informer.com/netfabb-basic/download/
